-- Add wedding profile columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cover_photo VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner1_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner2_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS wedding_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS venue_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS biography TEXT;
